services:
  db:
    container_name: django_testing
    image: postgres:latest
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5434:5432
